### ISSUE TITLE
Existing wallet cannot be imported

### ISSUE THREAD

**Issue by vysegrad** [pradel/blockstack-wallet#66]
Existing wallet can not be imported. When will this be added?

**Comment by pradel** [comment]
Closing this one in favour of https://github.com/pradel/blockstack-wallet/issues/36
I am planning to add this next week.

**Comment by pradel** [comment]
Hey @vysegrad you can now download the latest version where you can import a wallet and that support mainnet. https://github.com/pradel/blockstack-wallet/releases/tag/v0.5.0
