### ISSUE TITLE
I sent my wallet.What does this mean?

### ISSUE THREAD

**Issue by jeongkwonwi** [pradel/blockstack-wallet#92]
![888](https://user-images.githubusercontent.com/79822938/109451589-b8d46400-7a88-11eb-800f-9bc37db9f03a.jpg)
The stx token was sent from Binance to okcoin. Of course, I've attached a memo. Currently, Binance says it has been sent and okcoin cannot confirm it.

**Comment by jeongkwonwi** [comment]
![Uploading rrrr.jpg…]()

**Comment by pradel** [comment]
@jeongkwonwi this issue does not looks like it's related to this repository or did I miss something?
